language: julia
codecov: true
os:
  - linux
dist: xenial
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
env:
  global:
    - CODECOV_TOKEN="527112a2-2440-4364-9d06-9f03920fbb87"
    - PYTHON=""
