name = "CasADi"
uuid = "c49709b8-5c63-11e9-2fb2-69db5844192f"
authors = ["Iordanis Chatzinikolaidis <ch.iordanis@outlook.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
